name: Common Workflow

inputs:
  version:
    description: 'version'
    required: true
    default: 0

defaults:
  run:
    shell: bash

runs:
  using: 'composite'
  steps:
    - run: echo 'composite version ${{ inputs.version }}'
    - name: Create
      run: |
        echo we made a file > test.file
