name: Common Workflow

inputs:
  version:
    description: 'version'
    required: true
    default: 0

runs:
  using: 'composite'
  steps:
    - run: echo 'composite version ${{ inputs.version }}'
      shell: bash
    - name: Create
      run: |
        echo we made a file > test.file
      shell: bash
