name: Update release
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  Upload-Assets:
    runs-on: ubuntu-latest
    steps:
      - run: gh release upload bleeding-edge README.md --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
