name: TeatTar
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  Build:
    runs-on: macos-14
    steps:          
      - run: |
          curl -L http://www.cs.umd.edu/~mount/ANN/Files/1.1.2/ann_1.1.2.tar.gz --output ann_1.1.2.tar.gz
          tar xvfz ann_1.1.2.tar.gz