name: Clang
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  Build:
    runs-on: macos-14
    steps:
      - run: |
          sudo sed -E -i~ s/"clang::"/"clang"/g /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/sys/cdefs.h          
      - run: |
          curl -L http://www.qhull.org/download/qhull-2020-src-8.0.2.tgz --output qhull-2020-src-8.0.2.tgz
          tar xvfz qhull-2020-src-8.0.2.tgz
          cd qhull-2020.2
          make -j3 CC=gcc-11 CXX=g++-11
          sudo make install
          cd ..
          rm -rf qhull-2020-src-8.0.2.tgz qhull-2020.2
