name: CodeSign
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  Build:
    runs-on: macos-15
    env:
      MACOS_KEYCHAIN_PASSWORD=munky123
      MACOS_CERTIFICATE_PASSWORD=${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
      MACOS_CERTIFICATE=${{ secrets.MACOS_CERTIFICATE }}
    steps:
      - name: Sign Galacticus executable
        shell: bash
        run: |
          ORIGINAL_DEFAULT_KEYCHAIN=$(security default-keychain | sed 's/^ *"//; s/"$//')
          trap 'security default-keychain -s "$ORIGINAL_DEFAULT_KEYCHAIN"; security delete-keychain build.keychain' EXIT
          security create-keychain -p "${MACOS_KEYCHAIN_PASSWORD}" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "${MACOS_KEYCHAIN_PASSWORD}" build.keychain
          echo "${MACOS_CERTIFICATE}" | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P "${MACOS_CERTIFICATE_PASSWORD}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "${MACOS_KEYCHAIN_PASSWORD}" build.keychain
          rm certificate.p12
          # for file in ${{ inputs.files }}; do
          #   if [ -f "$file" ]; then
          #     codesign --force --options runtime --entitlements "${GITHUB_WORKSPACE}/.github/entitlements.plist" \
          #       --sign "${{ inputs.macos_developer_id }}" ${file}
          #     codesign --verify --deep --strict --verbose=2 ${file}
          #   else
          #     echo File ${file} not found for code-signing
          #     exit 1
          #   fi
          # done
