name: Common Workflow

on:
  workflow_call:
    inputs:
      version: # the variable you can use in place of a matrix
        required: true
        type: number

jobs:
  job1:
    steps:
      - run: echo 'job1 version ${{ inputs.version }}'
      - name: Create
        run: |
          echo we made a file > test.file
