name: CPAN
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  Build:
    runs-on: macos-14
    steps:
    - name: Set env
      shell: bash
      run: |
        echo "PERL_MM_USE_DEFAULT=1" >> $GITHUB_ENV
    - name: Install CPAN
      shell: bash
      run: |
        sudo perl -MCPAN -e shell
        sudo perl -MCPAN -e 'install Bundle::CPAN'
    - name: Install Perl modules
      shell: bash
      run: |
        export CFLAGS=-I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE
    - name: a
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","XML::LibXML::SAX::Parser")'
    - name: b
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","NestedMap")'
    - name: c
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","Scalar::Util")'
    - name: d
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","Term::ANSIColor")'
    - name: e
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","Text::Table")'
    - name: f
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","ExtUtils::ParseXS")'
    - name: g
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","Path::Tiny")'
    - name: h
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","PkgConfig")'
    - name: i
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","Alien::Base::Wrapper")'
    - name: j
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","Alien::Libxml2")'
    - name: k
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","XML::LibXML::SAX")'
        # Good to here.
    - name: 1
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","XML::LibXML::SAX::Parser")'
    - name: 2
      shell: bash
      run: |
        sudo perl -MXML::SAX -e "XML::SAX->add_parser('XML::SAX::PurePerl')->save_parsers()" || true
    - name: 3
      shell: bash
      run: |
        sudo perl -MXML::SAX -e "XML::SAX->add_parser('XML::LibXML::SAX::Parser')->save_parsers()"  || true
    - name: 4
      shell: bash
      run: |
        sudo perl -MXML::SAX -e "XML::SAX->add_parser('XML::LibXML::SAX')->save_parsers()"  || true
    - name: 5
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","XML::SAX::ParserFactory")'
    - name: 6
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","XML::Validator::Schema")'
    - name: 7
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","Text::Template")'
    - name: 8
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","List::Uniq")'
    - name: 9
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","IO::Util")'
    - name: 10
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","Class::Util")'
    - name: 11
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","CGI::Builder")'
    - name: 12
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","Simple")'
    - name: 13
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","Readonly")'
    - name: 14
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","File::Slurp")'
    - name: 15
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","XML::Simple")'
    - name: 16
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","List::MoreUtils")'
    - name: 17
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","Clone")'
    - name: 18
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","IO::Scalar")'
    - name: 19
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","Regexp::Common")'
    - name: 20
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","LaTeX::Encode")'
    - name: 21
      shell: bash
      run: |
        sudo perl -MCPAN -e 'force("install","Sub::Identify")'
