name: gcc13
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  Build:
    runs-on: macos-13
    steps:
      - run: |
          export PATH=$PATH:/opt/local/bin:/usr/local/bin
          macportsversion=2.9.1
          macportsbase=2.9.1-13-Ventura
          curl -L https://github.com/macports/macports-base/releases/download/v${macportsversion}/MacPorts-${macportsbase}.pkg --output MacPorts-${macportsbase}.pkg
          sudo installer -pkg ./MacPorts-${macportsbase}.pkg -target /
          rm ./MacPorts-${macportsbase}.pkg
          sudo port install gcc12
          cat /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc12/gcc12/main.log
