name: gcc13
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  Build:
    runs-on: macos-13
    steps:
      - name: Install
        run: |
          pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
          
