name: 'HDF5-Diff'
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
concurrency:
  group: hdf5Diff-${{ github.ref }}
  cancel-in-progress: true  
defaults:
  run:
    shell: bash
jobs:
  # Generate diffs of HDF5 files
  HDF5-Diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set environmental variables"
        run: |
          echo "GALACTICUS_EXEC_PATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Mark directory safe        
        run: |
          git config --global --add safe.directory $GALACTICUS_EXEC_PATH
      - name: Install tools
        run: |
          sudo apt -y update
          sudo apt install -y hdf5-tools
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            **/*.hdf5
      - name: Identify any new HDF5 files
        run: |
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            echo * Added: [${file}](https://myhdf5.hdfgroup.org/view?url=${{ github.event.pull_request.head.repo.html_url }}/FtestBench/blob/master/${file}) >> $GITHUB_STEP_SUMMARY
          done
