name: 'HDF5-Diff'
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
concurrency:
  group: hdf5Diff-${{ github.ref }}
  cancel-in-progress: true  
defaults:
  run:
    shell: bash
jobs:
  # Generate diffs of HDF5 files
  HDF5-Diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set environmental variables"
        run: |
          echo "GALACTICUS_EXEC_PATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Mark directory safe        
        run: |
          git config --global --add safe.directory $GALACTICUS_EXEC_PATH
      - name: Install tools
        run: |
          sudo apt -y update
          sudo apt install -y hdf5-tools
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            **/*.hdf5
      - name: Begin output if any files are changed
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo '# Changed HDF5 files' >> $GITHUB_STEP_SUMMARY
      - name: Identify any new HDF5 files
        run: |
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            echo Added: ${file}
            echo "* Added: [${file}](https://myhdf5.hdfgroup.org/view?url=${{ github.event.pull_request.head.repo.html_url }}/${{ github.head_ref }}/blob/${file})" >> $GITHUB_STEP_SUMMARY
          done
      - name: Identify any deleted HDF5 files
        run: |
          for file in ${{ steps.changed-files.outputs.deleted_files }}; do
            echo Deleted: ${file}
            echo "* Deleted: [${file}](https://myhdf5.hdfgroup.org/view?url=${{ github.event.pull_request.head.repo.html_url }}/${{ github.head_ref }}/blob/${file})" >> $GITHUB_STEP_SUMMARY
            echo "  * Original: [${file}](https://myhdf5.hdfgroup.org/view?url=${{ github.event.pull_request.base.repo.html_url }}/${{ github.base_ref }}/blob/${file})" >> $GITHUB_STEP_SUMMARY
          done
      - name: Identify any modified HDF5 files
        run: |
          for file in ${{ steps.changed-files.outputs.modified_files }}; do
            echo Modified: ${file}
            echo "* Modified: [${file}](https://myhdf5.hdfgroup.org/view?url=${{ github.event.pull_request.head.repo.html_url }}/${{ github.head_ref }}/blob/${file})" >> $GITHUB_STEP_SUMMARY
            echo "  * Original: [${file}](https://myhdf5.hdfgroup.org/view?url=${{ github.event.pull_request.base.repo.html_url }}/${{ github.base_ref }}/blob/${file})" >> $GITHUB_STEP_SUMMARY
            echo '```'  >> $GITHUB_STEP_SUMMARY
            FILE_SIZE=$(stat -c%s "${file}")
            if (( FILE_SIZE < 102400 )); then
              git difftool --tool="h5diff -r -c" ${file} ${{ github.base_ref }}/${file} >> $GITHUB_STEP_SUMMARY
            else
              echo "File is too large to display diff" >> $GITHUB_STEP_SUMMARY
            fi
            echo '```'  >> $GITHUB_STEP_SUMMARY
          done
