name: Master Workflow

on:
  workflow_dispatch:

jobs:
  version-matrix:
    strategy:
      # super important if you want to see all results, even if one fails
      # fail-fast is true by default
      fail-fast: false
      matrix:
        version: [10, 12, 14]
    uses: ./.github/workflows/common.yml
    with:
      version: ${{ matrix.version }}
    secrets: inherit

  continue:
    - name: Reuse
      uses: ./.github/workflows/common.yml
      with:
        version: 1234
      secrets: inherit
    - name: Finish up
      run: |
        ls
        cat test.file
