name: Master Workflow

on:
  workflow_dispatch:

jobs:
  continue:
    runs-on: ubuntu-latest
    compiler: gcc
    gcc: 12
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Finish up
        run: |
          gfortran -v
