name: Master Workflow

on:
  workflow_dispatch:

jobs:
  continue:
    runs-on: ubuntu-latest
    steps:
      - name: Reuse
        uses: ./.github/workflows/common
        with:
          version: 1234
      - name: Finish up
        run: |
          ls
          cat test.file
