name: Master Workflow

on:
  workflow_dispatch:

jobs:
  continue:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Reuse
        uses: ./.github/actions/common
        with:
          version: 1234
      - name: Finish up
        run: |
          ls
          cat test.file
